const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const reduce=matchMedia("(prefers-reduced-motion: reduce)").matches;
document.documentElement.style.setProperty("--vh",innerHeight+"px");
addEventListener("resize",()=>document.documentElement.style.setProperty("--vh",innerHeight+"px"));
const theme=localStorage.getItem("noctiluca-theme");
if(theme==="light")document.body.classList.add("light");
$("#theme")?.addEventListener("click",()=>{document.body.classList.toggle("light");localStorage.setItem("noctiluca-theme",document.body.classList.contains("light")?"light":"dark")});
$$(".nav-links a").forEach(a=>{if(a.pathname===location.pathname)a.classList.add("active")});
const canvas=$("#stars");if(canvas){const c=canvas.getContext("2d"),pts=[];function resize(){canvas.width=canvas.clientWidth*devicePixelRatio;canvas.height=canvas.clientHeight*devicePixelRatio;c.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);pts.length=0;for(let i=0;i<90;i++)pts.push({x:Math.random()*canvas.clientWidth,y:Math.random()*canvas.clientHeight,r:Math.random()*1.4+.2,s:Math.random()*.25+.05})}function draw(){c.clearRect(0,0,canvas.clientWidth,canvas.clientHeight);pts.forEach(p=>{p.y-=p.s;if(p.y<0)p.y=canvas.clientHeight;c.globalAlpha=.2+p.r/2;c.fillStyle="#eee9dc";c.beginPath();c.arc(p.x,p.y,p.r,0,7);c.fill()});if(!reduce)requestAnimationFrame(draw)}resize();draw();addEventListener("resize",resize)}
const lab=$("#labCanvas");if(lab){const c=lab.getContext("2d"),state={speed:.45,density:1,field:1};function fit(){lab.width=lab.clientWidth*devicePixelRatio;lab.height=lab.clientHeight*devicePixelRatio;c.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}function frame(t){const w=lab.clientWidth,h=lab.clientHeight;c.clearRect(0,0,w,h);const cx=w/2,cy=h/2;for(let i=0;i<160*state.density;i++){const a=i*.31+t*.00015*state.speed;const rr=(i*13+t*.015*state.speed)%(Math.min(w,h)*.45);const x=cx+Math.cos(a)*rr*(1+Math.sin(a*3)*.12*state.field);const y=cy+Math.sin(a)*rr*(.72+Math.cos(a*2)*.08);c.fillStyle=i%13===0?"#d9ff61":"#77746b";c.globalAlpha=i%13===0?.8:.22;c.fillRect(x,y,1.4,1.4)}c.globalAlpha=1;if(!reduce)requestAnimationFrame(frame)}fit();requestAnimationFrame(frame);addEventListener("resize",fit);$$("[data-range]").forEach(r=>r.addEventListener("input",e=>{state[e.target.dataset.range]=+e.target.value;const out=$("#v-"+e.target.dataset.range);if(out)out.textContent=e.target.value}))}
const entries=[...$$(".entry")];if(entries.length){const q=$("#query"),filters=[...$$(".filter")];let cat="all";function apply(){const term=q.value.toLowerCase();entries.forEach(e=>{e.hidden=!((cat==="all"||e.dataset.cat===cat)&&e.innerText.toLowerCase().includes(term))})}q.addEventListener("input",apply);filters.forEach(f=>f.addEventListener("click",()=>{filters.forEach(x=>x.classList.remove("active"));f.classList.add("active");cat=f.dataset.filter;apply()}))}
$$("[data-scroll]").forEach(b=>b.addEventListener("click",()=>$(b.dataset.scroll)?.scrollIntoView({behavior:"smooth"})));
addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();$("#query")?.focus()}});
const clock=$("#clock");if(clock)setInterval(()=>clock.textContent=new Intl.DateTimeFormat("fr-CH",{hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(new Date()),1000);
const year=$("#year");if(year)year.textContent=new Date().getFullYear();